### ISSUE TITLE
Mirror only displaying "Loading"

### ISSUE THREAD

**Issue by Aznbaka** [winstonma/MMM-HK-Transport#1]
Hi, 

Thanks for your work on this module! I've just added the module and it just remains on "Loading".

![Screenshot at 16-11-40](https://user-images.githubusercontent.com/72009580/94407057-8525a300-01a5-11eb-8be4-fa36e71718fb.png)

Do you know if this is because of the new update on the station format ? It seems like it is now different (with Chinese characters embedded in the stopID. (i.e.: Kowloon Central Post Office station link is now : https://citymapper.com/hong-kong/bus/stops/九龍中央郵政局-kowloon-central-post-office-n-1 )

Thanks!

**Comment by winstonma** [comment]
Yes you are right. This module is using API version 2 and currently they are using API version 3.

Let me update the API

**Comment by winstonma** [comment]
Hi @Aznbaka I made a new commit

Please check if it is working.

**Comment by Aznbaka** [comment]
Hi @winstonma I just tried again after updating the module but it still seems to be the same. Stuck on "Loading".

**Comment by winstonma** [comment]
Hmm... would you mind trying the following config and see if it work first?

```
    {
      module: 'MMM-HK-Transport',
      position: 'top_right',
      config: {
        stops: [
          {
            stopID: 'HKStop_KowloonCentralPostOffice_N_1'
          }
        ]
      }
    },
```

Currently the new version would show every line (including inactive), will try to fix that in later commit.

Thanks

**Comment by Aznbaka** [comment]
It seems working now! Apparently I had a typo in the stopID.

Thanks a lot for your help!! Looking forward to your new commit!

**Comment by winstonma** [comment]
Thanks for the bug report.

I focused on [MMM-HK-KMB](https://github.com/winstonma/MMM-HK-KMB) and didn't really update this for a while.

**Comment by Aznbaka** [comment]
One last question, I've noticed that the module won't actually display the bus lines with exact ETA time:

![Untitled2](https://user-images.githubusercontent.com/72009580/94512371-7ba44580-024e-11eb-9389-af8376c13cfe.png)
![Untitled](https://user-images.githubusercontent.com/72009580/94512385-8232bd00-024e-11eb-94d6-324514bc0162.png)

Is it the expected behavior ?

Thanks!

**Comment by winstonma** [comment]
Nono I just didn't read the returned value carefully. It is being fixed. Please update the module and let me know if there are problems.

Feature request are also welcomed

BTW I will hide the inactive route.

**Comment by winstonma** [comment]
@Aznbaka I just updated the module. Please use `npm install` as there are new dependency. This module should now support Van, Tram too.

Please reopen the ticket if you see the problem again.
