### ISSUE TITLE
Refreshing issue

### ISSUE THREAD

**Issue by Aznbaka** [winstonma/MMM-HK-Transport#2]
Hi @winstonma 
Sorry me again!
It seems like since the last commit, the module does not refresh anymore. It will just load the first time we start the MagicMirror and no more updates:

![image](https://user-images.githubusercontent.com/72009580/95177323-a5321380-07f0-11eb-8516-8271dcdf0873.png)

Is it working properly for you?

Thanks!

**Comment by winstonma** [comment]
Yes you are right I forgot to test that one. I just made one commit and it should fix the problem.

**Comment by Aznbaka** [comment]
All ok now ! Thanks a lot!
